"""Initial schema

Revision ID: 1ff3412e7cbd
Revises: 
Create Date: 2026-02-08 21:22:21.480554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ff3412e7cbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_company_profiles_team', 'company_profiles', ['team_id'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('partnership_level', sa.String(length=100), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('initiatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discovered_by_agent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_content',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('portfolio_recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiative_id')
    )
    op.create_table('research_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'STOPPED', 'FAILED', name='researchstatus'), nullable=False),
    sa.Column('follow_up_question', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('synthesized_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('PEOPLE', 'INITIATIVE', 'TECHNOLOGY', 'COMPETITIVE', 'FINANCIAL', 'MARKET', name='findingcategory'), nullable=False),
    sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('last_updated_cycle_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_session_id', sa.UUID(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=False),
    sa.Column('prime_agent_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_session_id'], ['research_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_cycle_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'STOPPED', 'EXHAUSTED', 'ERROR', name='pathstatus'), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('tools_used', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['research_cycle_id'], ['research_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('research_path_id', sa.UUID(), nullable=False),
    sa.Column('initiative_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('PEOPLE', 'INITIATIVE', 'TECHNOLOGY', 'COMPETITIVE', 'FINANCIAL', 'MARKET', name='findingcategory'), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['research_path_id'], ['research_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_findings_category', 'research_findings', ['category'], unique=False)
    op.create_index('ix_research_findings_initiative', 'research_findings', ['initiative_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_research_findings_initiative', table_name='research_findings')
    op.drop_index('ix_research_findings_category', table_name='research_findings')
    op.drop_table('research_findings')
    op.drop_table('research_paths')
    op.drop_table('research_cycles')
    op.drop_table('synthesized_intelligence')
    op.drop_table('research_sessions')
    op.drop_table('dashboard_content')
    op.drop_table('initiatives')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_table('portfolio_items')
    op.drop_index('ix_company_profiles_team', table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_table('teams')
    # ### end Alembic commands ###
